//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPolicy
    {
        public int CarId { get; set; }
        public int PoliceNo { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public System.DateTime UretimYili { get; set; }
        public string Plaka { get; set; }
    }
}
