//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PoliceNo { get; set; }
        public string SirketAdi { get; set; }
        public string PoliceUrunGrubu { get; set; }
        public System.DateTime TanzimTarihi { get; set; }
        public System.DateTime VadeTarihi { get; set; }
        public double PrimTutari { get; set; }
        public string Teminatlar { get; set; }
        public string Tip { get; set; }
        public double Borc { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
